services:
  idearockers:
    build:
      context: .
      dockerfile: dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - NEXT_PUBLIC_APP_URL=${SITE_URL_DEV:-https://idearockers.ixr.dev}
      - NEXT_PUBLIC_DEV_MODE=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${DEV_PORT:-6202}:3000"
    restart: unless-stopped
